/**
 * Atlas Validation Research — Session Mutations
 *
 * Internal mutations that manage the validation research session lifecycle.
 * These run in Convex's default V8 runtime (no "use node").
 *
 * Exported for use by validationResearchOrchestration.ts (the Node.js action).
 */

import { internalMutation, mutation } from "./_generated/server";
import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import { internal } from "./_generated/api";

// Provider version written into new research rows (must match OpenAIValidationResearchProvider.VERSION)
const PROVIDER_VERSION = "openai-gpt4o-mini-1.2.0";

// ── forceRegenerateValidation ─────────────────────────────────────────────────

/**
 * Public mutation called by the "Rebuild Validation" button in the UI.
 *
 * Marks all existing research rows for this invention as stale (researchStatus="stale"),
 * then schedules a fresh runValidationResearchOrchestration action.
 * Auth-gated: only the owning user can trigger regeneration.
 */
export const forceRegenerateValidation = mutation({
  args: {
    inventionId: v.id("inventions"),
  },
  handler: async (ctx, { inventionId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const invention = await ctx.db.get(inventionId);
    if (!invention || invention.userId !== userId) {
      throw new Error("Invention not found or access denied");
    }

    const now = Date.now();

    // Mark all existing research rows for this invention as stale so the
    // 24h cache is bypassed on the next orchestration run.
    const existingRows = await ctx.db
      .query("validationResearch")
      .withIndex("by_inventionId", (q) => q.eq("inventionId", inventionId))
      .collect();

    for (const row of existingRows) {
      await ctx.db.patch(row._id, {
        researchStatus: "stale",
        overallStatus: "STALE",
        updatedAt: now,
      });
    }

    // Schedule fresh orchestration (bypasses 24h cache since rows are now stale)
    await ctx.scheduler.runAfter(
      0,
      internal.validationResearchOrchestration.runValidationResearchOrchestration,
      { inventionId }
    );

    return { queued: true };
  },
});

// ── initValidationResearchSession ─────────────────────────────────────────────

export const initValidationResearchSession = internalMutation({
  args: {
    inventionId: v.id("inventions"),
  },
  returns: v.union(
    v.object({
      status: v.literal("existing"),
      researchId: v.id("validationResearch"),
    }),
    v.object({
      status: v.literal("created"),
      researchId: v.id("validationResearch"),
      inventionTitle: v.string(),
      problemStatement: v.string(),
      inventionDescription: v.string(),
    })
  ),
  handler: async (ctx, { inventionId }) => {
    const TWENTY_FOUR_HOURS_MS = 24 * 60 * 60 * 1000;
    const now = Date.now();

    const invention = await ctx.db.get(inventionId);
    if (!invention) throw new Error("Invention not found");

    // 24h cache: reuse COMPLETED research within the last 24 hours
    const existing = await ctx.db
      .query("validationResearch")
      .withIndex("by_inventionId_status", (q) =>
        q.eq("inventionId", inventionId).eq("researchStatus", "completed")
      )
      .order("desc")
      .first();

    if (
      existing &&
      existing.completedAt !== undefined &&
      existing.completedAt >= now - TWENTY_FOUR_HOURS_MS &&
      // Only reuse rows generated by the current OpenAI provider — not legacy mock or error-content rows
      existing.providerVersion === PROVIDER_VERSION
    ) {
      console.log(`[Stage2] Cached record reused: researchId=${existing._id} inventionId=${inventionId} completedAt=${existing.completedAt}`);
      return { status: "existing" as const, researchId: existing._id };
    }

    // Create a new PENDING research row
    const researchId = await ctx.db.insert("validationResearch", {
      inventionId,
      stageId: "2",
      researchStatus: "pending",
      overallStatus: "PENDING",
      sections: {} as Record<string, unknown>,
      totalSectionCount: 11,
      completedSectionCount: 0,
      startedAt: now,
      updatedAt: now,
      providerVersion: PROVIDER_VERSION,
      researchVersion: 1,
    });

    console.log(`[Stage2] Research record created: researchId=${researchId} inventionId=${inventionId}`);
    return {
      status: "created" as const,
      researchId,
      inventionTitle: invention.title,
      problemStatement: invention.problemStatement ?? "",
      inventionDescription: invention.solutionDescription ?? "",
    };
  },
});

// ── patchValidationSection ────────────────────────────────────────────────────

export const patchValidationSection = internalMutation({
  args: {
    researchId: v.id("validationResearch"),
    sectionKey: v.string(),
    sectionEntry: v.any(),
    completedSectionCount: v.number(),
    lastCompletedSection: v.string(),
    overallStatus: v.string(),
    updatedAt: v.number(),
  },
  handler: async (
    ctx,
    {
      researchId,
      sectionKey,
      sectionEntry,
      completedSectionCount,
      lastCompletedSection,
      overallStatus,
      updatedAt,
    }
  ) => {
    const record = await ctx.db.get(researchId);
    if (!record) {
      throw new Error(`Validation research row not found: ${researchId}`);
    }

    const currentSections: Record<string, unknown> =
      (record.sections as Record<string, unknown>) ?? {};

    const updatedSections = {
      ...currentSections,
      [sectionKey]: sectionEntry,
    };

    await ctx.db.patch(researchId, {
      sections: updatedSections,
      completedSectionCount,
      lastCompletedSection,
      overallStatus,
      updatedAt,
    });
  },
});

// ── markValidationResearchInProgress ─────────────────────────────────────────

export const markValidationResearchInProgress = internalMutation({
  args: {
    researchId: v.id("validationResearch"),
    updatedAt: v.number(),
  },
  handler: async (ctx, { researchId, updatedAt }) => {
    await ctx.db.patch(researchId, {
      overallStatus: "IN_PROGRESS",
      researchStatus: "running",
      updatedAt,
    });
  },
});

// ── finaliseValidationResearch ────────────────────────────────────────────────

export const finaliseValidationResearch = internalMutation({
  args: {
    researchId: v.id("validationResearch"),
    overallStatus: v.string(),
    completedAt: v.number(),
    researchStatus: v.string(),
  },
  handler: async (ctx, { researchId, overallStatus, completedAt, researchStatus }) => {
    await ctx.db.patch(researchId, {
      overallStatus,
      researchStatus,
      completedAt,
      updatedAt: completedAt,
    });
  },
});

// ── recordValidationResearchFailure ──────────────────────────────────────────

export const recordValidationResearchFailure = internalMutation({
  args: {
    inventionId: v.id("inventions"),
    researchId: v.optional(v.id("validationResearch")),
    error: v.string(),
    failedAt: v.number(),
  },
  handler: async (ctx, { inventionId, researchId, error, failedAt }) => {
    if (researchId) {
      await ctx.db.patch(researchId, {
        researchStatus: "failed",
        overallStatus: "FAILED",
        error,
        completedAt: failedAt,
        updatedAt: failedAt,
      });
      return researchId;
    }

    const invention = await ctx.db.get(inventionId);
    if (!invention) {
      throw new Error(`Invention not found while recording validation failure: ${inventionId}`);
    }

    return await ctx.db.insert("validationResearch", {
      inventionId,
      stageId: "2",
      researchStatus: "failed",
      overallStatus: "FAILED",
      sections: {} as Record<string, unknown>,
      totalSectionCount: 11,
      completedSectionCount: 0,
      startedAt: failedAt,
      completedAt: failedAt,
      updatedAt: failedAt,
      providerVersion: PROVIDER_VERSION,
      researchVersion: 1,
      error,
    });
  },
});
