version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Flutter/Dart
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Firebase Functions
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"

  # Backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
